### ISSUE TITLE
crashes in main menu

### ISSUE THREAD

**Issue by Pa4ok** [TheCBProject/NotEnoughItems#173] opened 2018-08-19 16:06 UTC
https://gist.github.com/Pa4ok/cf1a903739a707c74a4cbbfb46cabe72
in issues of jei i found that it is a nei issue
https://github.com/mezz/JustEnoughItems/issues/1337

**Comment by covers1624** [comment] 2018-08-19 21:38
Duplicate of https://github.com/TheCBProject/NotEnoughItems/issues/170

**Closed by covers1624** 2018-08-19 21:38 UTC
