### ISSUE TITLE
NEI crash on starting up in a mobpack 1.12.2 StoneBlock

### ISSUE THREAD

**Issue by KusanagiRyu** [TheCBProject/NotEnoughItems#189] opened 2018-10-14 14:09 UTC
As stated in the title.
here's the link in Pastebin.com
https://pastebin.com/GhgWkFVD

**Comment by covers1624** [comment] 2018-10-14 14:28
Duplicate of https://github.com/TheCBProject/NotEnoughItems/issues/183, https://github.com/TheCBProject/NotEnoughItems/issues/184, https://github.com/TheCBProject/NotEnoughItems/issues/186. Please look for closed issues first before posting.

**Closed by covers1624** 2018-10-14 14:28 UTC
