### ISSUE TITLE
Crash when closing game

### ISSUE THREAD

**Issue by Fatmice** [TheCBProject/NotEnoughItems#172] opened 2018-08-17 03:43 UTC
https://github.com/mezz/JustEnoughItems/issues/1332

**Comment by covers1624** [comment] 2018-08-17 04:04
Blame @mezz for changing things, Duplicate of https://github.com/TheCBProject/NotEnoughItems/issues/170 Ill have a fix out in a few days.

**Closed by covers1624** 2018-08-17 04:04 UTC

**Comment by Fatmice** [comment] 2018-08-17 06:04
It crashes not just closing the game but also as soon as I click a button to launch multiplayer or singleplayer.  I'll rollback.
