### ISSUE TITLE
nei crashes with new jei version

### ISSUE THREAD

**Issue by Zer0Lyfe** [TheCBProject/NotEnoughItems#170] opened 2018-08-14 01:47 UTC
version of mods
nei - 2.4.1.238
jei - 4.112.0.214
CodeChickenLib - 1.12.2-3.2.1.350-universal

crash logs:
In my larger 1.12.2 modpack:
https://gist.githubusercontent.com/Zer0Lyfe/b0694669102606c4f875cfeafdaa7866/raw/216282f77cab5a11652497d3bcc72ec2457b5107/crash%2520nei.log
With just nei and jei with dependencies:
https://gist.github.com/Zer0Lyfe/3a1447981bc1bfa4f0af51d2cd07e590

**Comment by PanSzelescik** [comment] 2018-08-14 17:59
Duplicate: https://github.com/mezz/JustEnoughItems/issues/1330

**Comment by covers1624** [comment] 2018-08-14 21:42
Not a duplicate? Its clearly an NEI issue, and i don't follow the JEI tracker, Anyway, seems to be caused by this change: https://github.com/mezz/JustEnoughItems/commit/3330e8711830ae837aeb234c26a2963b99048e36#diff-db99546a1ebc5fc6302a58f158ce5d32L63 Ill look into it this week, for now, just don't use the bleeding edge of JEI.

**Comment by DEViANCEVxXXxM** [comment] 2018-08-18 11:01
same
`---- Minecraft Crash Report ----
// I blame ChickenBones, author of Not Enough Items.

Time: 2018-08-18 15:47:22 UZT
Description: Updating screen events

java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
    at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:125)
    at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1587_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:500)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1758)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: lumien.custommainmenu.gui.GuiCustom

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 687320528 bytes (655 MB) / 3759669248 bytes (3585 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -Xmx4G -Xms1G -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2756 Optifine OptiFine_1.12.2_HD_U_E2 143 mods loaded, 143 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                  | Source                                   | Signature                                |
       |:------ |:-------------------- |:------------------------ |:---------------------------------------- |:---------------------------------------- |
       | UCHIJA | minecraft            | 1.12.2                   | minecraft.jar                            | None                                     |
       | UCHIJA | mcp                  | 9.42                     | minecraft.jar                            | None                                     |
       | UCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.4.2756.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJA | forge                | 14.23.4.2756             | forge-1.12.2-14.23.4.2756.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJA | creativecoredummy    | 1.0.0                    | minecraft.jar                            | None                                     |
       | UCHIJA | itemphysic           | 1.4.0                    | minecraft.jar                            | None                                     |
       | UCHIJA | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                            | None                                     |
       | UCHIJA | foamfixcore          | 7.7.4                    | minecraft.jar                            | None                                     |
       | UCHIJA | ambientsounds        | 2.0.0                    | (client) Ambient Sounds.jar              | None                                     |
       | UCHIJA | betteradvancements   | 0.0.8.50                 | (client) Better Advancements.jar         | None                                     |
       | UCHIJA | betterplacement      | 1.0.0-1                  | (client) Better Placement.jar            | None                                     |
       | UCHIJA | blur                 | 1.0.4-14                 | (client) Blur.jar                        | None                                     |
       | UCHIJA | consolehud           | 1.1.1                    | (client) Console HUD.jar                 | None                                     |
       | UCHIJA | custommainmenu       | 2.0.8                    | (client) Custom Main Menu.jar            | None                                     |
       | UCHIJA | discordsuite         | 2.2.4                    | (client) Discord Suite.jar               | None                                     |
       | UCHIJA | dsurround            | 3.4.9.14                 | (client) Dynamic Surroundings.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | UCHIJA | presets              | 3.4.9.14                 | (client) Dynamic Surroundings.jar        | None                                     |
       | UCHIJA | enchdesc             | 1.1.9                    | (client) Enchantment Descriptions.jar    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJA | waila                | 1.8.26                   | (client) Hwyla.jar                       | None                                     |
       | UCHIJA | jei                  | 4.12.0.215               | Just Enough Items.jar                    | None                                     |
       | UCHIJA | mantle               | 1.12-1.3.2.24            | Mantle.jar                               | None                                     |
       | UCHIJA | natura               | 1.12.2-4.3.2.62          | Natura.jar                               | None                                     |
       | UCHIJA | toughasnails         | 3.1.0.115                | Tough As Nails.jar                       | None                                     |
       | UCHIJA | forestry             | 5.8.1.337                | Forestry.jar                             | None                                     |
       | UCHIJA | jeibees              | 0.9.0.5                  | (client) Just Enough Bees.jar            | None                                     |
       | UCHIJA | blockdrops           | 1.4.0                    | (client) Just Enough Block Drops.jar     | None                                     |
       | UCHIJA | harvestcraft         | 1.12.2w                  | Pam's HarvestCraft.jar                   | None                                     |
       | UCHIJA | jehc                 | 1.12.2                   | (client) Just Enough Harvestcreaft.jar   | None                                     |
       | UCHIJA | jepb                 | 1.2.1                    | (client) Just Enough Pattern Banners.jar | None                                     |
       | UCHIJA | jeresources          | 0.8.10.50                | (client) Just Enough Resources.jar       | None                                     |
       | UCHIJA | tconstruct           | 1.12.2-2.10.1.87         | Tinker's Construct.jar                   | None                                     |
       | UCHIJA | tinkersjei           | 1.0                      | (client) Just Enough Tinkers.jar         | None                                     |
       | UCHIJA | mobends              | 0.25                     | (client) Mo Bends.jar                    | None                                     |
       | UCHIJA | mousetweaks          | 2.8                      | (client) Mouse Tweaks.jar                | None                                     |
       | UCHIJA | norecipebook         | 1.2.1                    | (client) No Recipe Book.jar              | None                                     |
       | UCHIJA | resourceloader       | 1.5.3                    | (client) Resource Loader.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJA | soundfilters         | 0.10_for_1.12            | (client) Sound Filters.jar               | None                                     |
       | UCHIJA | baubles              | 1.5.2                    | Baubles.jar                              | None                                     |
       | UCHIJA | thaumcraft           | 6.1.BETA22               | Thaumcraft.jar                           | None                                     |
       | UCHIJA | thaumicjei           | 1.2.1                    | (client) Thaumic JEI.jar                 | None                                     |
       | UCHIJA | wailaharvestability  | 1.1.12                   | (client) Waila Harvestability.jar        | None                                     |
       | UCHIJA | wawla                | 2.5.257                  | (client) Wawla.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJA | akashictome          | 1.2-10                   | Akashic Tome.jar                         | None                                     |
       | UCHIJA | applecore            | 3.1.3                    | Apple Core.jar                           | None                                     |
       | UCHIJA | applejuiceskin       | 1.0.0.4                  | Apple Juice Skin.jar                     | None                                     |
       | UCHIJA | appleskin            | 1.0.9                    | Apple Skin.jar                           | None                                     |
       | UCHIJA | astralsorcery        | 1.9.4                    | Astral Sorcery.jar                       | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | UCHIJA | morphtool            | 1.2-16                   | Morph o Tool.jar                         | None                                     |
       | UCHIJA | quark                | r1.5-126                 | Quark.jar                                | None                                     |
       | UCHIJA | autoreglib           | 1.3-19                   | AutoRegLib.jar                           | None                                     |
       | UCHIJA | bhc                  | 1.1.1                    | Baubley Heart.jar                        | 7b14aaee2dd17b12a140baecab28948fff3a263f |
       | UCHIJA | bdlib                | 1.14.3.12                | Bdlib.jar                                | None                                     |
       | UCHIJA | bettercombatmod      | 1.5.6                    | Better Combat.jar                        | None                                     |
       | UCHIJA | binniecore           | 2.5.0.168                | Binnie Mods.jar                          | None                                     |
       | UCHIJA | binniedesign         | 2.5.0.168                | Binnie Mods.jar                          | None                                     |
       | UCHIJA | genetics             | 2.5.0.168                | Binnie Mods.jar                          | None                                     |
       | UCHIJA | botany               | 2.5.0.168                | Binnie Mods.jar                          | None                                     |
       | UCHIJA | extrabees            | 2.5.0.168                | Binnie Mods.jar                          | None                                     |
       | UCHIJA | extratrees           | 2.5.0.168                | Binnie Mods.jar                          | None                                     |
       | UCHIJA | biomesoplenty        | 7.0.1.2398               | Biomes O Plenty.jar                      | None                                     |
       | UCHIJA | botania              | r1.10-354                | Botania.jar                              | None                                     |
       | UCHIJA | codechickenlib       | 3.2.1.351                | Code Chicken Lib.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJA | redstoneflux         | 2.0.2                    | Redstone Flux.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | brandonscore         | 2.4.4                    | Brandons Core.jar                        | None                                     |
       | UCHIJA | bullseye             | 3.0.6                    | Bullseye.jar                             | None                                     |
       | UCHIJA | cashcraft            | mc1.12.2-4.0.0.1         | CashCraft.jar                            | None                                     |
       | UCHIJA | chameleon            | 1.12-4.1.3               | Chameleon.jar                            | None                                     |
       | UCHIJA | chesttransporter     | 2.8.8                    | Chest Transporter.jar                    | None                                     |
       | UCHIJA | sanlib               | 1.5.0                    | SanLib.jar                               | None                                     |
       | UCHIJA | claysoldiers         | 3.0.0-beta.1.1           | Clay Soldiers.jar                        | None                                     |
       | UCHIJA | clumps               | 3.1.1                    | Clumps.jar                               | None                                     |
       | UCHIJA | cofhcore             | 4.5.3                    | CoFH Core.jar                            | None                                     |
       | UCHIJA | cofhworld            | 1.2.0                    | CoFH World.jar                           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | conarm               | 1.0.2                    | Constructs' Armory.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJA | creativecore         | 1.9.9                    | Creative Core.jar                        | None                                     |
       | UCHIJA | cucumber             | 1.1.0                    | Cucumber.jar                             | None                                     |
       | UCHIJA | thermalfoundation    | 2.5.0                    | Thermal Foundation.jar                   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | draconicevolution    | 2.3.13                   | Draconic Evolution.jar                   | None                                     |
       | UCHIJA | embers               | 0.221                    | Embers.jar                               | None                                     |
       | UCHIJA | enderstorage         | 2.4.5.135                | Ender Storage.jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJA | extrautils2          | 1.0                      | Extra Utils.jar                          | None                                     |
       | UCHIJA | fastfurnace          | 1.1.0                    | Fast Furnace.jar                         | None                                     |
       | UCHIJA | fastbench            | 1.5.1                    | Fast Workbench.jar                       | None                                     |
       | UCHIJA | foamfix              | 0.10.0-1.12.2            | Foam Fix.jar                             | None                                     |
       | UCHIJA | gendustry            | 1.6.5.8                  | Gendustry.jar                            | None                                     |
       | UCHIJA | guideapi             | 1.12-2.1.7-62            | Guide API.jar                            | None                                     |
       | UCHIJA | hammercore           | 2.0.2.2                  | Hammer Core.jar                          | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHIJA | hardcoredarkness     | 2.0                      | Hardcore Darkness.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJA | instantunify         | 1.1.2                    | Instant Unify.jar                        | None                                     |
       | UCHIJA | ironbackpacks        | 1.12.2-3.0.8-12          | Iron Backpacks.jar                       | None                                     |
       | UCHIJA | ironchest            | 1.12.2-7.0.46.831        | Iron Chest.jar                           | None                                     |
       | UCHIJA | mysticalagriculture  | 1.6.13                   | Mystical Agriculture.jar                 | None                                     |
       | UCHIJA | mysticalagradditions | 1.2.8                    | Mystical Agradditions.jar                | None                                     |
       | UCHIJA | jaopcaagriculture    | 1.12.2-1.2.1.13          | JAOPCA Agriculture.jar                   | None                                     |
       | UCHIJA | jaopca               | 1.12.2-2.2.8.90          | JAOPCA.jar                               | None                                     |
       | UCHIJA | jaopcaadditions      | 1.12.2-2.2.1.9           | JAOPCA Additions.jar                     | None                                     |
       | UCHIJA | oredictinit          | 1.12.2-2.2.1.68          | JAOPCA.jar                               | None                                     |
       | UCHIJA | journeymap           | 1.12.2-5.5.2             | Journey Map.jar                          | None                                     |
       | UCHIJA | jeid                 | 1.0.1-16                 | Just Enough IDs.jar                      | None                                     |
       | UCHIJA | lex                  | 1.0.6                    | LibEx.jar                                | None                                     |
       | UCHIJA | magicbees            | 1.0                      | Magic Bees.jar                           | None                                     |
       | UCHIJA | mcmultipart          | 2.5.1                    | MC MultiPart.jar                         | None                                     |
       | UCHIJA | mercurius            | 1.0.6                    | Mercurius.jar                            | None                                     |
       | UCHIJA | testdummy            | 1.12                     | MmmMmmMmmMmm.jar                         | None                                     |
       | UCHIJA | naturescompass       | 1.5.1                    | Natures Compass.jar                      | None                                     |
       | UCHIJA | netherchest          | 0.2.3                    | Nether Chest.jar                         | None                                     |
       | UCHIJA | thermalexpansion     | 5.5.0                    | Thermal Expansion.jar                    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | netherfoundation     | 1.2.0                    | Nether Foundation.jar                    | None                                     |
       | UCHIJA | nex                  | 2.0.6                    | NetherEx.jar                             | None                                     |
       | UCHIJA | nei                  | 2.4.1                    | Not Enough Items.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJA | p455w0rdslib         | 2.0.32                   | p455w0rds lib.jar                        | None                                     |
       | UCHIJA | pandorasbox          | 2.1.6.2-1.12             | Pandoras Box.jar                         | None                                     |
       | UCHIJA | plustic              | 6.5.2.0                  | Plustic.jar                              | None                                     |
       | UCHIJA | primal               | 0.6.72                   | Primal Core.jar                          | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | UCHIJA | progressivebosses    | 1.3.2                    | Progressive Bosses.jar                   | None                                     |
       | UCHIJA | quarkoddities        | 1                        | Quark Oddities.jar                       | None                                     |
       | UCHIJA | reccomplex           | 1.4.7                    | Recurrent Complex.jar                    | None                                     |
       | UCHIJA | redstonearsenal      | 2.5.1                    | Redstone Arsenal.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | roots                | 0.104                    | Roots.jar                                | None                                     |
       | UCHIJA | sanplayermodel       | 1.1.1                    | SanLib.jar                               | None                                     |
       | UCHIJA | sereneseasons        | 1.2.6                    | Serene Seasons.jar                       | None                                     |
       | UCHIJA | servertabinfo        | 1.2.2                    | Server Tab Info.jar                      | None                                     |
       | UCHIJA | snad                 | 1.12.1-1.7.09.16a        | Snad.jar                                 | None                                     |
       | UCHIJA | solarflux            | 4.10r                    | Solar Flux Reborn.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHIJA | sonarcore            | 5.0.15                   | Sonar Core.jar                           | None                                     |
       | UCHIJA | soot                 | 1.3hotfix                | Soot.jar                                 | None                                     |
       | UCHIJA | spartanshields       | 1.4.1                    | Spartan Shields.jar                      | None                                     |
       | UCHIJA | storagedrawers       | 1.12-5.3.5               | Storage Drawers.jar                      | None                                     |
       | UCHIJA | storagedrawersextra  | @VERSION@                | Storage Drawers Extras.jar               | None                                     |
       | UCHIJA | taiga                | 1.3.2                    | Taiga.jar                                | None                                     |
       | UCHIJA | thaumadditions       | 4r                       | Thaumic Additions.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHIJA | tcinventoryscan      | 2.0.10                   | Thaumic Inventory Scanning.jar           | None                                     |
       | UCHIJA | thaumictinkerer      | 1.12.2-5.0-353c71c       | Thaumic Tinkerer.jar                     | None                                     |
       | UCHIJA | thermalcultivation   | 0.3.0                    | Thermal Cultivation.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | thermaldynamics      | 2.5.1                    | Thermal Dynamics.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | thermalinnovation    | 0.3.0                    | Thermal Innovation.jar                   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | tinkertoolleveling   | 1.12.2-1.0.5.DEV.30c7957 | Tinker Tool Leveling.jar                 | None                                     |
       | UCHIJA | tanaddons            | 3.4.24                   | Tough Expansion.jar                      | None                                     |
       | UCHIJA | vanillafix           | 1.0.9-97                 | Vanilla Fix.jar                          | None                                     |
       | UCHIJA | wanionlib            | 1.12.2-1.5               | Wanion Lib.jar                           | None                                     |
       | UCHIJA | zerocore             | 1.12-0.1.2.2             | Zero Core.jar                            | None                                     |
       | UCHIJA | hungeroverhaul       | 1.12.2-1.3.3.jenkins148  | Hunger Overhaul.jar                      | None                                     |
       | UCHIJA | wrapup               | 1.12-1.1.3               | Wrap Up.jar                              | None                                     |
  Loaded coremods (and transformers): HCASM (Hammer Core.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      JEIDLoadingPlugin (Just Enough IDs.jar)
                                        
                                      Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (Foam Fix.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin ((client) Resource Loader.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (Hardcore Darkness.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      IvToolkit (IvToolkit.jar)
                                        
                                      SSLoadingPlugin (Serene Seasons.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      LoadingPlugin (Quark.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (Apple Core.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      VanillaFixLoadingPlugin (Vanilla Fix.jar)
                                        
                                      BlurPlugin ((client) Blur.jar)
                                        com.tterrag.blur.BlurTransformer
                                      DynamicSurroundingsCore ((client) Dynamic Surroundings.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      CreativePatchingLoader (Creative Core.jar)
                                        
                                      AstralCore (Astral Sorcery.jar)
                                        
                                      ItemPatchingLoader (Item Physic.jar)
                                        com.creativemd.itemphysic.ItemTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.58' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 3553 names; 5419 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Thaumic Additions: Reconstructed (thaumadditions) @4r
  List of loaded APIs: * AppleCoreAPI (3.1.0) from Apple Core.jar
                       * Baubles|API (1.4.0.2) from Baubles.jar
                       * betteradvancements|API (0.0.8.50) from (client) Better Advancements.jar
                       * BetterWithModsAPI (Beta 0.6) from Apple Skin.jar
                       * BotaniaAPI (89) from Botania.jar
                       * CashCraftAPI (1.0) from CashCraft.jar
                       * chesttransporter|api (2) from Chest Transporter.jar
                       * claysoldiers_api (1.0.0-beta.1) from Clay Soldiers.jar
                       * cofhapi (2.5.0) from CoFH Core.jar
                       * DraconicEvolution|API (1.3) from Draconic Evolution.jar
                       * EmbersAPI (0.1) from Embers.jar
                       * ForestryAPI|apiculture (5.0.0) from Forestry.jar
                       * ForestryAPI|arboriculture (4.3.0) from Forestry.jar
                       * ForestryAPI|book (5.8.1) from Forestry.jar
                       * ForestryAPI|circuits (3.1.0) from Forestry.jar
                       * ForestryAPI|climate (5.0.0) from Forestry.jar
                       * ForestryAPI|core (5.7.0) from Forestry.jar
                       * ForestryAPI|farming (5.8.0) from Forestry.jar
                       * ForestryAPI|food (1.1.0) from Forestry.jar
                       * ForestryAPI|fuels (3.0.0) from Forestry.jar
                       * ForestryAPI|genetics (5.7.0) from Forestry.jar
                       * ForestryAPI|greenhouse (5.2.0) from Forestry.jar
                       * ForestryAPI|gui (5.8.0) from Forestry.jar
                       * ForestryAPI|hives (4.1.0) from Forestry.jar
                       * ForestryAPI|lepidopterology (1.4.0) from Forestry.jar
                       * ForestryAPI|mail (3.1.0) from Forestry.jar
                       * ForestryAPI|modules (5.7.0) from Forestry.jar
                       * ForestryAPI|multiblock (3.0.0) from Forestry.jar
                       * ForestryAPI|recipes (5.4.0) from Forestry.jar
                       * ForestryAPI|storage (5.0.0) from Forestry.jar
                       * ForestryAPI|world (2.1.0) from Forestry.jar
                       * gendustryAPI (2.3.0) from Gendustry.jar
                       * Guide-API|API (2.0.0) from Guide API.jar
                       * jeresources|API (0.8.10.50) from (client) Just Enough Resources.jar
                       * journeymap|client-api (1.4) from Journey Map.jar
                       * journeymap|client-api-display (1.4) from Journey Map.jar
                       * journeymap|client-api-event (1.4) from Journey Map.jar
                       * journeymap|client-api-model (1.4) from Journey Map.jar
                       * journeymap|client-api-util (1.4) from Journey Map.jar
                       * JustEnoughItemsAPI (4.13.0) from Just Enough Items.jar
                       * MouseTweaks|API (1.0) from (client) Mouse Tweaks.jar
                       * ProjectEAPI (1.9.4-1.0.0) from p455w0rds lib.jar
                       * QuarkAPI (2) from Quark.jar
                       * sanlib_api (1.0.0) from SanLib.jar
                       * sonarapi (1.0.1) from Sonar Core.jar
                       * StorageDrawersAPI (2.1.0) from Storage Drawers.jar
                       * StorageDrawersAPI|event (2.1.0) from Storage Drawers.jar
                       * StorageDrawersAPI|registry (2.1.0) from Storage Drawers.jar
                       * StorageDrawersAPI|render (2.1.0) from Storage Drawers.jar
                       * StorageDrawersAPI|storage (2.1.0) from Storage Drawers.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from Storage Drawers.jar
                       * Thaumcraft|API (6.0.2) from Thaumcraft.jar
                       * WailaAPI (1.3) from (client) Hwyla.jar
                       * zerocore|API|multiblock (1.10.2-0.0.2) from Zero Core.jar
                       * zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from Zero Core.jar
                       * zerocore|API|multiblock|tier (1.10.2-0.0.2) from Zero Core.jar
                       * zerocore|API|multiblock|validation (1.10.2-0.0.2) from Zero Core.jar
  Suspected Mods: Not Enough Items (nei)
  Launched Version: optipxel
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.58, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Faithful Modded.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
`

**Comment by PolyacovYury** [comment] 2018-09-22 12:49
I can see that the fix for this is in build 239. When will it be verified and made "recommended"? People are waiting..

**Comment by covers1624** [comment] 2018-09-29 06:29
Pending approval on curse.

**Closed by covers1624** 2018-09-29 06:29 UTC
Labels: bug, fixed in dev
